/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as ReviewsReviewIdIndexRouteImport } from './routes/reviews/$reviewId/index'
import { Route as ReviewsReviewIdReportRouteImport } from './routes/reviews/$reviewId/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdIndexRoute = ReviewsReviewIdIndexRouteImport.update({
  id: '/reviews/$reviewId/',
  path: '/reviews/$reviewId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdReportRoute = ReviewsReviewIdReportRouteImport.update({
  id: '/reviews/$reviewId/report',
  path: '/reviews/$reviewId/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/reviews/$reviewId/report': typeof ReviewsReviewIdReportRoute
  '/reviews/$reviewId/': typeof ReviewsReviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsIndexRoute
  '/reviews/$reviewId/report': typeof ReviewsReviewIdReportRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/reviews/$reviewId/report': typeof ReviewsReviewIdReportRoute
  '/reviews/$reviewId/': typeof ReviewsReviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/reports'
    | '/reviews/'
    | '/reviews/$reviewId/report'
    | '/reviews/$reviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/reports'
    | '/reviews'
    | '/reviews/$reviewId/report'
    | '/reviews/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/reports'
    | '/reviews/'
    | '/reviews/$reviewId/report'
    | '/reviews/$reviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ReviewsReviewIdReportRoute: typeof ReviewsReviewIdReportRoute
  ReviewsReviewIdIndexRoute: typeof ReviewsReviewIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId/': {
      id: '/reviews/$reviewId/'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId/'
      preLoaderRoute: typeof ReviewsReviewIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId/report': {
      id: '/reviews/$reviewId/report'
      path: '/reviews/$reviewId/report'
      fullPath: '/reviews/$reviewId/report'
      preLoaderRoute: typeof ReviewsReviewIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ReviewsReviewIdReportRoute: ReviewsReviewIdReportRoute,
  ReviewsReviewIdIndexRoute: ReviewsReviewIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
